title: My super blog
author: 
  name: vorthkor
  email: virtorf@etlgr.com
description: > # this means to ignore newlines until "baseurl:"
  Não mais um teste de blog usando Jekyll e Github Pages. Agora um blog mesmo.

show_excerpts: false # set to false to remove excerpts on the homepage

minima:
  skin: dark

social_links:
  github: vorthkor # DO NOT include the @ character, or else the build will fail!

# Build settings
theme: minima

header_pages:
  - about.md
  - portfolio.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
