title: My super blog
author: 
  name: vorthkor
  email: virtorf@etlgr.com
description: > # this means to ignore newlines until "baseurl:"
  Não mais um teste de blog usando Jekyll e Github Pages. Agora um blog mesmo.

show_excerpts: false # set to false to remove excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"
  skin: dark

  # generate social links in footer
  social_links:
    twitter: mf4raday
    github:  vorthkor

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md
  - portfolio.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
